protocol bgp uk07 from full_ibgp {
    neighbor fdc0:d227:306:2a07::1 as inet_asn;
    # ca04 to uk07: only send dn42 v4 full table but accept all inet routes; send full v6 table
    ipv4 {
        import filter full_ibgp_import_v4;
        export filter dn42_ibgp_export_v4;
    };
}
