protocol bgp pflb_ca01 from dnpeers {
    neighbor fe80::1240:5%wg1240pflbca01 as 4242421240;
    bfd graceful;
    direct;
    ipv4 {
        import where dn42_filter4im(4242421240, 11, 40, 0);
        export where dn42_filter4ex(4242421240, 11);
    };
    ipv6 {
        import where dn42_filter6im(4242421240, 11, 40, 0);
        export where dn42_filter6ex(4242421240, 11);
    };
}
