protocol bgp rbits_tor from dnpeers {
    neighbor fe80::207%wg0207rbitstor as 4242420207;
    direct;
    ipv4 {
        import where dn42_filter4im(4242420207, 28, 40, 0);
        export where dn42_filter4ex(4242420207, 28);
    };
    ipv6 {
        import where dn42_filter6im(4242420207, 28, 40, 0);
        export where dn42_filter6ex(4242420207, 28);
    };
}
