protocol bgp cowgl_yul from dnpeers {
    neighbor fe80::5:3999%wg3999cowglyul as 4242423999;
    direct;
    ipv4 {
        import where dn42_filter4im(0xca04, 4242423999, 81, 0, 0);
        export where dn42_filter4ex(0xca04, 4242423999, 81);
    };
    ipv6 {
        import where dn42_filter6im(0xca04, 4242423999, 81, 0, 0);
        export where dn42_filter6ex(0xca04, 4242423999, 81);
    };
}
