protocol bgp nedifinita_ix from dnpeers {
    neighbor fd10:127:42:ffff::1 as 4204549999;
    local role rs_client;
    bfd on;

    ipv4 {
        table dn42_v4;
        extended next hop on;
        add paths rx;
        import where dn42_filter4im(0xca04, 4204549999, 639, 0, 40);
        export filter {
            if bgp_path.len > 0 then reject;
            dn42_filter4ex(0xca04, 4204549999, 639);
        };
    };

    ipv6 {
        table dn42_v6;
        add paths rx;
        import where dn42_filter6im(0xca04, 4204549999, 639, 0, 40);
        export filter {
            if bgp_path.len > 0 then reject;
            dn42_filter6ex(0xca04, 4204549999, 639);
        };
    };
}
