protocol bgp iedon_nyc from dnpeers {
    neighbor fe80::2189:124%wg2189iedonnyc as 4242422189;
    direct;
    ipv4 {
        import where dn42_filter4im(4242422189, 302, 0, 0);
        export where dn42_filter4ex(4242422189, 302);
    };
    ipv6 {
        import where dn42_filter6im(4242422189, 302, 0, 0);
        export where dn42_filter6ex(4242422189, 302);
    };
}
