protocol bgp highdef_ymq from dnpeers {
    neighbor fe80::123%wg1080hidefymq as 4242421080;
    direct;
    ipv4 {
        import where dn42_filter4im(0xca04, 4242421080, 20, 0, 0);
        export where dn42_filter4ex(0xca04, 4242421080, 20);
    };
    ipv6 {
        import where dn42_filter6im(0xca04, 4242421080, 20, 0, 0);
        export where dn42_filter6ex(0xca04, 4242421080, 20);
    };
}
