[Service]
ExecStartPre=-/usr/sbin/ip route delete 0.0.0.0/0 via inet6 fe80::ca04 dev wginternal0 table 211585
ExecStartPre=-/usr/sbin/ip route delete ::/0 via fe80::ca04 dev wginternal0 table 211585
ExecStart=/usr/sbin/ip route add ::/0 via fe80::ca04 dev wginternal0 table 211585
ExecStart=/usr/sbin/ip route add 0.0.0.0/0 via inet6 fe80::ca04 dev wginternal0 table 211585
