[Service]
LockPersonality=true
MemoryDenyWriteExecute=true
#PrivateDevices=false
#PrivateUsers=false
PrivateTmp=true
ProcSubset=pid
ProtectClock=true
ProtectControlGroups=true
ProtectHome=true
ProtectHostname=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectKernelTunables=true
ProtectProc=invisible
ProtectSystem=strict
RestrictAddressFamilies=AF_INET AF_INET6 AF_NETLINK AF_UNIX
RestrictNamespaces=true
RestrictRealtime=true
RestrictSUIDSGID=true
ReadWritePaths=/var/lib/zerotier-one
SystemCallArchitectures=native
SystemCallFilter=@system-service
UMask=0077
