[commands]
upgrade_type = security
random_sleep = 0
network_online_timeout = 60
download_updates = yes
apply_updates = no

reboot = never

[emitters]
emit_via = stdio

[email]
email_from = root@srv3.maiyun.me
email_to = admin@maiyun.me
email_host = localhost
email_port = 25
email_tls = no
