protocol bgp uk07 from full_ibgp {
    neighbor fdc0:d227:306:2a07::1 as inet_asn;
    # uc01 to uk07: send all routes but only accept dn42 routes
    ipv4 {
        import filter dn42_ibgp_import_v4;
        export filter full_ibgp_export_v4;
    };
    ipv6 {
        import filter dn42_ibgp_import_v6;
        export filter full_ibgp_export_v6;
    };
}
