protocol bgp iyoroy_lax from dnpeers {
    neighbor fe80::2024%wg2024iyoroylax as 4242422024;
    direct;
    ipv4 {
        import where dn42_filter4im(4242422024, 33, 0, 0);
        export where dn42_filter4ex(4242422024, 33);
    };
    ipv6 {
        import where dn42_filter6im(4242422024, 33, 0, 0);
        export where dn42_filter6ex(4242422024, 33);
    };
}
