protocol bgp lezi_uslos from dnpeers {
    neighbor fe80::3377%wg3377lezilos as 4242423377;
    bfd graceful;
    direct;
    ipv4 {
        import where dn42_filter4im(4242423377, 133, 0, 0);
        export where dn42_filter4ex(4242423377, 133);
    };
    ipv6 {
        import where dn42_filter6im(4242423377, 133, 0, 0);
        export where dn42_filter6ex(4242423377, 133);
    };
}
