protocol bgp sunnet_lax from dnpeers {
    neighbor fe80::3088:193%wg3088sunnetlax as 4242423088;
    direct;
    ipv4 {
        import where dn42_filter4im(4242423088, 132, 0, 0);
        export where dn42_filter4ex(4242423088, 132);
    };
    ipv6 {
        import where dn42_filter6im(4242423088, 132, 0, 0);
        export where dn42_filter6ex(4242423088, 132);
    };
}
