protocol bgp pflb_us03 from dnpeers {
    neighbor fe80::1240:4%wg1240pflbus03 as 4242421240;
    bfd graceful;
    direct;
    ipv4 {
        import where dn42_filter4im(4242421240, 32, 0, 0);
        export where dn42_filter4ex(4242421240, 32);
    };
    ipv6 {
        import where dn42_filter6im(4242421240, 32, 0, 0);
        export where dn42_filter6ex(4242421240, 32);
    };
}
