protocol bgp ca04 from full_ibgp {
    neighbor fdc0:d227:306:ca04::1 as inet_asn;
    # jp02 to ca04: only accept dn42 full table but send all inet routes
    ipv4 {
        import filter dn42_ibgp_import_v4;
        export filter full_ibgp_export_v4;
    };
    ipv6 {
        import filter dn42_ibgp_import_v6;
        export filter full_ibgp_export_v6;
    };
}
