protocol bgp sess_tyo from dnpeers {
    neighbor fe80::2466%wg2466sesstyo as 4242422466;
    direct;
    ipv4 {
        import where dn42_filter4im(4242422466, 26, 40, 0);
        export where dn42_filter4ex(4242422466, 26);
    };
    ipv6 {
        import where dn42_filter6im(4242422466, 26, 40, 0);
        export where dn42_filter6ex(4242422466, 26);
    };
}
