protocol bgp iedon_tyo from dnpeers {
    neighbor fe80::2189:ee%wg2189iedontyo as 4242422189;
    direct;
    ipv4 {
        import where dn42_filter4im(4242422189, 6, 50, 0);
        export where dn42_filter4ex(4242422189, 6);
    };
    ipv6 {
        import where dn42_filter6im(4242422189, 6, 50, 0);
        export where dn42_filter6ex(4242422189, 6);
    };
}
