protocol bgp lezi_hk from dnpeers {
    neighbor fe80::3377%wg3377lezihk as 4242423377;
    bfd graceful;
    direct;
    ipv4 {
        import where dn42_filter4im(0xaa02, 4242423377, 86, 0, 40);
        export where dn42_filter4ex(0xaa02, 4242423377, 86);
    };
    ipv6 {
        import where dn42_filter6im(0xaa02, 4242423377, 86, 0, 40);
        export where dn42_filter6ex(0xaa02, 4242423377, 86);
    };
}
