protocol bgp kskbneo_tyo from dnpeers {
    neighbor fe80::1111%wg1111kskbneoty as 4201271111;
    direct;
    ipv4 {
        import where dn42_filter4im(4242421111, 64, 40, 0);
        export where dn42_filter4ex(4242421111, 64);
    };
    ipv6 {
        import where dn42_filter6im(4242421111, 64, 40, 0);
        export where dn42_filter6ex(4242421111, 64);
    };
}
