protocol bgp imlonghao_tyo from dnpeers {
    neighbor fe80::1888%wg1888imlhtyo as 4242421888;
    direct;
    ipv4 {
        import where dn42_filter4im(4242421888, 21, 40, 0);
        export where dn42_filter4ex(4242421888, 21);
    };
    ipv6 {
        import where dn42_filter6im(4242421888, 21, 40, 0);
        export where dn42_filter6ex(4242421888, 21);
    };
}
