protocol bgp rbits_tyo from dnpeers {
    neighbor fe80::207%wg0207rbitstyo as 4242420207;
    direct;
    ipv4 {
        import where dn42_filter4im(0xaa02, 4242420207, 20, 40, 0);
        export where dn42_filter4ex(0xaa02, 4242420207, 20);
    };
    ipv6 {
        import where dn42_filter6im(0xaa02, 4242420207, 20, 40, 0);
        export where dn42_filter6ex(0xaa02, 4242420207, 20);
    };
}
