protocol bgp iedon_grc {
    local as dn42_asn;
    neighbor fe80::2189:191%wg2189iedongrc as 4242422189;
    direct;
    ipv4 {
        table dn42_v4;
        add paths tx;
        import none;
        export where dn42_ebgp_export_v4();
    };
    ipv6 {
        table dn42_v6;
        add paths tx;
        import none;
        export where dn42_ebgp_export_v6();
    };
}
