protocol bgp ca04 from full_ibgp {
    neighbor fdc0:d227:306:ca04::1 as inet_asn;
    # uk07 to ca04: only accept dn42 v4 full table but send all inet routes; exchange full v6 table
    ipv4 {
        import filter dn42_ibgp_import_v4;
        export filter full_ibgp_export_v4;
    };
}
