protocol bgp uc01 from full_ibgp {
    neighbor fdc0:d227:306:2c01::1 as inet_asn;
    # uk07 to uc01: only send dn42 full table but accept all inet routes
    ipv4 {
        import filter full_ibgp_import_v4;
        export filter dn42_ibgp_export_v4;
    };
    ipv6 {
        import filter full_ibgp_import_v6;
        export filter dn42_ibgp_export_v6;
    };
}
