# vi: ft=sshdconfig
# /etc/ssh/sshd_config.d/security-local.conf

HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

AuthorizedKeysFile .ssh/authorized_keys
PasswordAuthentication no
PermitEmptyPasswords no
PermitRootLogin no

LoginGraceTime 30
MaxAuthTries 3
MaxSessions 5
X11Forwarding no
