# /etc/bird/conf.d/00-shared-util.conf

## Constants
### Large community codes
define lcm_im_lq = 30;
define lcm_ex_lq = 31;
define lcm_im_soi = 40;
define lcm_im_peer = 41;
define lcm_im_rpki = 42;
define lcm_ex_soo = 50;
define lcm_ex_peer = 51;
include "/etc/bird/conf.d/00-nodeinfo.subconf";

function reject_with_info(string reason) {
    print reason, " ", net, " from ", proto, " ", bgp_path;
    reject;
}
